development:
  adapter: postgresql
  encoding: unicode
  database: onelist_development
  pool: 5
  username: jacksrf
  password: trey33

test:
  adapter: postgresql
  encoding: unicode
  database: onelist_test
  pool: 5
  username: jacksrf
  password: trey33
