development:
  adapter: postgresql
  encoding: unicode
  database: onelist_development
  pool: 5
  username: rolanjackson
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: onelist_test
  pool: 5
  username: rolanjackson
  password: 
